import 'dotenv/config';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '../generated/prisma/client';

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const roles = [
  { id: 'role-1', name: 'Frontend', slug: 'frontend' },
  { id: 'role-2', name: 'Backend', slug: 'backend' },
  { id: 'role-3', name: 'Full Stack', slug: 'full-stack' },
  { id: 'role-4', name: 'Mobile', slug: 'mobile' },
  { id: 'role-5', name: 'DevOps', slug: 'devops' },
  { id: 'role-6', name: 'Data Science', slug: 'data-science' },
  { id: 'role-7', name: 'UI/UX Design', slug: 'ui-ux-design' },
  { id: 'role-8', name: 'QA / Testing', slug: 'qa-testing' },
  { id: 'role-9', name: 'Security', slug: 'security' },
  { id: 'role-10', name: 'Product Management', slug: 'product-management' },
];

const roleIdBySlug: Record<string, string> = Object.fromEntries(roles.map(r => [r.slug, r.id]));

const jobs = [
  {
    id: 'job-1',
    title: 'Frontend Developer',
    company: 'Acme Corp',
    location: 'Buenos Aires, Argentina',
    roleId: roleIdBySlug['frontend'],
    description:
      'Build and maintain user-facing features for our SaaS platform using React and TypeScript. You will collaborate closely with designers and backend engineers to deliver polished, performant UIs.',
    requirements: [
      '3+ years of React experience',
      'Strong TypeScript skills',
      'Familiarity with REST APIs',
      'Git workflow knowledge',
    ],
    salaryRange: '$2,500 - $3,500 USD/month',
    modality: 'remote',
    experience: 'mid',
    createdAt: new Date('2026-03-01T09:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-2',
    title: 'Senior Backend Engineer',
    company: 'Globant',
    location: 'Montevideo, Uruguay',
    roleId: roleIdBySlug['backend'],
    description:
      'Design and develop scalable microservices for a high-traffic e-commerce platform. You will own entire domains end-to-end and mentor junior engineers.',
    requirements: [
      '5+ years of Node.js experience',
      'Experience with PostgreSQL and Redis',
      'Knowledge of microservices patterns',
      'AWS or GCP experience',
    ],
    salaryRange: '$4,500 - $6,000 USD/month',
    modality: 'hybrid',
    experience: 'senior',
    createdAt: new Date('2026-03-02T10:30:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-3',
    title: 'Full Stack Developer',
    company: 'Mercado Libre',
    location: 'Santiago, Chile',
    roleId: roleIdBySlug['full-stack'],
    description:
      'Join our growth team to build internal tools and customer-facing features across the stack. You will work in two-week sprints with a cross-functional team.',
    requirements: [
      'Experience with Vue or React',
      'Backend experience with Python or Node',
      'SQL proficiency',
      'Good communication skills',
    ],
    salaryRange: '$3,000 - $4,000 USD/month',
    modality: 'remote',
    experience: 'mid',
    createdAt: new Date('2026-03-02T14:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-4',
    title: 'React Native Developer',
    company: 'Naranja X',
    location: 'Córdoba, Argentina',
    roleId: roleIdBySlug['mobile'],
    description:
      'Develop and maintain our mobile banking app used by millions of Argentinian customers. You will implement new features and ensure a smooth, reliable experience.',
    requirements: [
      '3+ years of React Native',
      'Experience with iOS and Android releases',
      'Knowledge of mobile CI/CD',
      'Accessibility awareness',
    ],
    salaryRange: '$3,200 - $4,200 USD/month',
    modality: 'hybrid',
    experience: 'mid',
    createdAt: new Date('2026-03-03T08:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-5',
    title: 'DevOps Engineer',
    company: 'Auth0 (Okta)',
    location: 'Remote',
    roleId: roleIdBySlug['devops'],
    description:
      'Manage and evolve our Kubernetes-based infrastructure. You will drive reliability, security, and efficiency across dozens of microservices.',
    requirements: [
      '4+ years in DevOps/SRE roles',
      'Kubernetes expertise',
      'CI/CD pipeline experience',
      'Monitoring and alerting experience',
    ],
    salaryRange: '$5,000 - $7,000 USD/month',
    modality: 'remote',
    experience: 'senior',
    createdAt: new Date('2026-03-03T11:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-6',
    title: 'Data Scientist',
    company: 'Despegar',
    location: 'Buenos Aires, Argentina',
    roleId: roleIdBySlug['data-science'],
    description:
      'Build predictive models for pricing, demand forecasting, and customer segmentation in the travel industry. Work with large datasets and present insights to stakeholders.',
    requirements: [
      'Degree in Statistics, Math, or CS',
      '3+ years of ML experience',
      'Python and SQL fluency',
      'Experience with cloud ML platforms',
    ],
    salaryRange: '$3,500 - $5,000 USD/month',
    modality: 'hybrid',
    experience: 'mid',
    createdAt: new Date('2026-03-03T13:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-7',
    title: 'UI/UX Designer',
    company: 'Ualá',
    location: 'Buenos Aires, Argentina',
    roleId: roleIdBySlug['ui-ux-design'],
    description:
      'Lead the design of new product features for our fintech app. Conduct user research, create wireframes and prototypes, and collaborate with engineering to ship great experiences.',
    requirements: [
      'Portfolio of shipped mobile products',
      '3+ years of product design',
      'Figma proficiency',
      'User research experience',
    ],
    salaryRange: '$2,800 - $3,800 USD/month',
    modality: 'remote',
    experience: 'mid',
    createdAt: new Date('2026-03-04T09:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-8',
    title: 'QA Automation Engineer',
    company: 'Santander Tech',
    location: 'Madrid, Spain',
    roleId: roleIdBySlug['qa-testing'],
    description:
      'Design and implement automated test suites for a critical banking platform. You will work with developers to enforce quality standards and reduce release cycle times.',
    requirements: [
      'Experience with Playwright or Cypress',
      'API testing knowledge',
      'CI/CD integration experience',
      'ISTQB certification is a plus',
    ],
    salaryRange: '€2,800 - €3,600/month',
    modality: 'hybrid',
    experience: 'mid',
    createdAt: new Date('2026-03-04T10:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-9',
    title: 'Cloud Security Engineer',
    company: 'Telecom Argentina',
    location: 'Buenos Aires, Argentina',
    roleId: roleIdBySlug['security'],
    description:
      'Harden our cloud infrastructure and develop security policies across AWS workloads. Perform threat modeling, vulnerability assessments, and incident response.',
    requirements: [
      '4+ years in cloud security',
      'AWS security certifications preferred',
      'Knowledge of OWASP Top 10',
      'Scripting skills (Python or Bash)',
    ],
    salaryRange: '$4,000 - $5,500 USD/month',
    modality: 'hybrid',
    experience: 'senior',
    createdAt: new Date('2026-03-04T12:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-10',
    title: 'Technical Product Manager',
    company: 'Rappi',
    location: 'Bogotá, Colombia',
    roleId: roleIdBySlug['product-management'],
    description:
      'Own the roadmap for our logistics optimization suite. Work with data scientists and engineers to define, prioritize, and ship features that reduce delivery times.',
    requirements: [
      '3+ years as a PM in tech',
      'Ability to read technical specs and code',
      'Experience with OKR frameworks',
      'Data-driven decision making',
    ],
    salaryRange: '$4,000 - $5,000 USD/month',
    modality: 'remote',
    experience: 'senior',
    createdAt: new Date('2026-03-04T14:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-11',
    title: 'Junior Frontend Developer',
    company: 'Nuvemshop',
    location: 'São Paulo, Brazil',
    roleId: roleIdBySlug['frontend'],
    description:
      'Help build and improve the merchant dashboard for thousands of e-commerce stores. Great opportunity to grow under senior mentorship in a fast-paced environment.',
    requirements: [
      'Knowledge of HTML, CSS, JavaScript',
      'React basics',
      'Eagerness to learn',
      'Good communication in English',
    ],
    salaryRange: 'R$4,500 - R$6,000/month',
    modality: 'remote',
    experience: 'junior',
    createdAt: new Date('2026-03-05T08:30:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-12',
    title: 'Semi Senior Backend Developer',
    company: 'Wolox (Accenture)',
    location: 'Buenos Aires, Argentina',
    roleId: roleIdBySlug['backend'],
    description:
      'Develop RESTful APIs and integrations for clients in the retail and logistics industries. Participate in code reviews and architecture discussions.',
    requirements: [
      '2-4 years of backend development',
      'Ruby on Rails or Node.js',
      'PostgreSQL knowledge',
      'Testing practices',
    ],
    salaryRange: '$2,800 - $3,800 USD/month',
    modality: 'hybrid',
    experience: 'semi-senior',
    createdAt: new Date('2026-03-05T09:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-13',
    title: 'Android Developer',
    company: 'Personal (Telecom)',
    location: 'Buenos Aires, Argentina',
    roleId: roleIdBySlug['mobile'],
    description:
      'Build features for the Mi Personal app, used daily by millions of mobile subscribers. Focus on performance, reliability, and modern Android architecture.',
    requirements: [
      '3+ years of Android development',
      'Kotlin proficiency',
      'Jetpack Compose experience',
      'MVVM architecture knowledge',
    ],
    salaryRange: '$3,000 - $4,000 USD/month',
    modality: 'onsite',
    experience: 'mid',
    createdAt: new Date('2026-03-05T10:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-14',
    title: 'Site Reliability Engineer',
    company: 'Satellogic',
    location: 'Remote',
    roleId: roleIdBySlug['devops'],
    description:
      'Ensure the reliability and performance of satellite data processing pipelines. Define SLOs, manage on-call rotations, and lead post-mortems.',
    requirements: [
      'Experience in SRE or platform engineering',
      'Linux systems knowledge',
      'Observability tooling expertise',
      'On-call experience',
    ],
    salaryRange: '$5,500 - $7,500 USD/month',
    modality: 'remote',
    experience: 'senior',
    createdAt: new Date('2026-03-05T11:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-15',
    title: 'Machine Learning Engineer',
    company: 'Tryolabs',
    location: 'Montevideo, Uruguay',
    roleId: roleIdBySlug['data-science'],
    description:
      'Build end-to-end ML pipelines for clients across retail, healthcare, and logistics. Deploy and monitor models in production environments.',
    requirements: [
      'Strong Python skills',
      'Experience with TensorFlow or PyTorch',
      'MLOps knowledge',
      'Ability to communicate with non-technical clients',
    ],
    salaryRange: '$4,000 - $5,500 USD/month',
    modality: 'remote',
    experience: 'mid',
    createdAt: new Date('2026-03-05T12:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-16',
    title: 'Senior UI Designer',
    company: 'Mural',
    location: 'Remote',
    roleId: roleIdBySlug['ui-ux-design'],
    description:
      'Shape the visual language and component library of our collaborative workspace platform. Partner with product and engineering to ensure design consistency at scale.',
    requirements: [
      '5+ years in product/UI design',
      'Experience building design systems',
      'Figma expert',
      'Cross-functional collaboration experience',
    ],
    salaryRange: '$5,000 - $6,500 USD/month',
    modality: 'remote',
    experience: 'senior',
    createdAt: new Date('2026-03-06T08:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-17',
    title: 'Manual QA Analyst',
    company: 'OLX Autos',
    location: 'Buenos Aires, Argentina',
    roleId: roleIdBySlug['qa-testing'],
    description:
      'Execute manual and exploratory testing on web and mobile apps. Write detailed bug reports and work with developers to ensure high-quality releases.',
    requirements: [
      '1+ years QA experience',
      'Familiarity with Agile/Scrum',
      'Bug tracking tools (Jira)',
      'Mobile testing knowledge',
    ],
    salaryRange: '$1,200 - $1,800 USD/month',
    modality: 'hybrid',
    experience: 'junior',
    createdAt: new Date('2026-03-06T09:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-18',
    title: 'Application Security Analyst',
    company: 'Banco Galicia',
    location: 'Buenos Aires, Argentina',
    roleId: roleIdBySlug['security'],
    description:
      'Perform secure code reviews and penetration tests on web and mobile banking applications. Ensure compliance with PCI-DSS and internal security policies.',
    requirements: [
      'Knowledge of OWASP Top 10',
      'Web application pentesting experience',
      'Familiarity with SAST/DAST tools',
      'Report writing skills',
    ],
    salaryRange: '$3,000 - $4,000 USD/month',
    modality: 'onsite',
    experience: 'semi-senior',
    createdAt: new Date('2026-03-06T10:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-19',
    title: 'Associate Product Manager',
    company: 'dLocal',
    location: 'Montevideo, Uruguay',
    roleId: roleIdBySlug['product-management'],
    description:
      'Support the payments product team in defining requirements, coordinating releases, and analyzing performance metrics for our Latin America markets.',
    requirements: [
      '1-2 years of PM or business analyst experience',
      'Basic SQL knowledge',
      'Strong written communication',
      'Payments industry interest',
    ],
    salaryRange: '$2,000 - $2,800 USD/month',
    modality: 'hybrid',
    experience: 'junior',
    createdAt: new Date('2026-03-06T11:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-20',
    title: 'Vue.js Developer',
    company: 'Rootstrap',
    location: 'Montevideo, Uruguay',
    roleId: roleIdBySlug['frontend'],
    description:
      'Develop responsive web applications for international clients in the health and wellness space. Participate in client meetings and sprint planning.',
    requirements: [
      '2+ years of Vue.js',
      'REST API integration experience',
      'Responsive design skills',
      'English proficiency (B2+)',
    ],
    salaryRange: '$2,500 - $3,500 USD/month',
    modality: 'remote',
    experience: 'semi-senior',
    createdAt: new Date('2026-03-06T14:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-21',
    title: 'Python Backend Developer',
    company: 'Xapo Bank',
    location: 'Remote',
    roleId: roleIdBySlug['backend'],
    description:
      'Build and maintain backend services for a global crypto-friendly bank. Work in a fully distributed team across multiple time zones.',
    requirements: [
      '3+ years of Python',
      'Django or FastAPI experience',
      'Knowledge of async patterns',
      'Experience with financial systems is a plus',
    ],
    salaryRange: '$4,000 - $5,500 USD/month',
    modality: 'remote',
    experience: 'mid',
    createdAt: new Date('2026-03-07T08:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-22',
    title: 'iOS Developer',
    company: 'Pedidosya',
    location: 'Montevideo, Uruguay',
    roleId: roleIdBySlug['mobile'],
    description:
      'Build and improve the iOS experience for the leading food delivery app in Latin America. Optimize for performance, stability, and accessibility.',
    requirements: [
      'Swift proficiency',
      '3+ years of iOS development',
      'UIKit and SwiftUI experience',
      'App Store release experience',
    ],
    salaryRange: '$3,500 - $4,500 USD/month',
    modality: 'hybrid',
    experience: 'mid',
    createdAt: new Date('2026-03-07T09:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-23',
    title: 'Infrastructure Engineer',
    company: 'NotCo',
    location: 'Santiago, Chile',
    roleId: roleIdBySlug['devops'],
    description:
      'Build the cloud infrastructure that powers our AI-driven food tech platform. Define standards for IaC, networking, and cost optimization.',
    requirements: [
      'Experience with AWS or Azure',
      'Terraform proficiency',
      'Networking fundamentals',
      'Security best practices knowledge',
    ],
    salaryRange: '$3,500 - $4,500 USD/month',
    modality: 'hybrid',
    experience: 'semi-senior',
    createdAt: new Date('2026-03-07T10:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-24',
    title: 'Data Analyst',
    company: 'Tiendanube',
    location: 'Buenos Aires, Argentina',
    roleId: roleIdBySlug['data-science'],
    description:
      'Analyze merchant and consumer behavior to guide product decisions. Build dashboards and reports for leadership and operations teams.',
    requirements: [
      'SQL expertise',
      'Experience with BI tools',
      'Basic Python or R',
      'Strong presentation skills',
    ],
    salaryRange: '$1,800 - $2,500 USD/month',
    modality: 'hybrid',
    experience: 'junior',
    createdAt: new Date('2026-03-07T11:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-25',
    title: 'Product Designer',
    company: 'Increase',
    location: 'Buenos Aires, Argentina',
    roleId: roleIdBySlug['ui-ux-design'],
    description:
      'Design seamless experiences for merchants using our payment solutions. Work alongside the CPO to define the product vision and ensure user-centered design.',
    requirements: [
      'Portfolio required',
      '2+ years in product design',
      'Figma advanced skills',
      'Fintech experience preferred',
    ],
    salaryRange: '$2,500 - $3,500 USD/month',
    modality: 'hybrid',
    experience: 'semi-senior',
    createdAt: new Date('2026-03-07T13:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-26',
    title: 'Senior QA Engineer',
    company: 'Mercado Pago',
    location: 'Buenos Aires, Argentina',
    roleId: roleIdBySlug['qa-testing'],
    description:
      'Lead quality assurance efforts across multiple payment flows. Define testing strategies, mentor junior QA engineers, and contribute to CI/CD quality gates.',
    requirements: [
      '5+ years in QA',
      'Automation with Selenium or Playwright',
      'Performance testing experience',
      'Mentoring skills',
    ],
    salaryRange: '$4,000 - $5,500 USD/month',
    modality: 'hybrid',
    experience: 'senior',
    createdAt: new Date('2026-03-07T14:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-27',
    title: 'Penetration Tester',
    company: 'ESET Latinoamérica',
    location: 'Buenos Aires, Argentina',
    roleId: roleIdBySlug['security'],
    description:
      'Conduct internal and client-facing penetration tests on network, web, and mobile targets. Produce clear, actionable reports for technical and executive audiences.',
    requirements: [
      'Ethical hacking certifications (OSCP preferred)',
      'Network and web pentesting experience',
      'Scripting skills',
      'Report writing',
    ],
    salaryRange: '$4,500 - $6,000 USD/month',
    modality: 'hybrid',
    experience: 'senior',
    createdAt: new Date('2026-03-08T08:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-28',
    title: 'Product Manager – Growth',
    company: 'Bitso',
    location: 'Remote',
    roleId: roleIdBySlug['product-management'],
    description:
      'Drive user acquisition and retention strategies for our crypto exchange platform across Mexico, Brazil, and Argentina. Run experiments and own growth metrics.',
    requirements: [
      '3+ years as PM',
      'Experience with growth/experimentation frameworks',
      'Analytical mindset',
      'Crypto industry interest',
    ],
    salaryRange: '$4,000 - $5,500 USD/month',
    modality: 'remote',
    experience: 'mid',
    createdAt: new Date('2026-03-08T09:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-29',
    title: 'Angular Developer',
    company: 'Grupo Supervielle',
    location: 'Buenos Aires, Argentina',
    roleId: roleIdBySlug['frontend'],
    description:
      'Develop and maintain digital banking web applications. Ensure accessibility compliance and collaborate with UX designers to implement pixel-perfect interfaces.',
    requirements: [
      '3+ years of Angular',
      'TypeScript expertise',
      'RxJS knowledge',
      'Banking domain knowledge is a plus',
    ],
    salaryRange: '$2,800 - $3,800 USD/month',
    modality: 'onsite',
    experience: 'mid',
    createdAt: new Date('2026-03-08T10:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-30',
    title: 'Java Backend Engineer',
    company: 'Pragma',
    location: 'Medellín, Colombia',
    roleId: roleIdBySlug['backend'],
    description:
      'Design and build Java-based microservices for enterprise clients in the banking and insurance sectors. Apply hexagonal architecture and DDD principles.',
    requirements: [
      '4+ years of Java',
      'Spring Boot expertise',
      'Knowledge of DDD and clean architecture',
      'Microservices experience',
    ],
    salaryRange: 'COP 8,000,000 - 11,000,000/month',
    modality: 'hybrid',
    experience: 'senior',
    createdAt: new Date('2026-03-08T11:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-31',
    title: 'Full Stack Engineer (Node + React)',
    company: 'Mango',
    location: 'Remote',
    roleId: roleIdBySlug['full-stack'],
    description:
      'Build product features across the stack for a B2B SaaS startup. You will have a high degree of autonomy and direct impact on product direction.',
    requirements: [
      '3+ years of full stack experience',
      'React and Node.js',
      'Database design skills',
      'Startup mindset',
    ],
    salaryRange: '$3,500 - $5,000 USD/month',
    modality: 'remote',
    experience: 'mid',
    createdAt: new Date('2026-03-08T13:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-32',
    title: 'Flutter Developer',
    company: 'Fudo',
    location: 'Buenos Aires, Argentina',
    roleId: roleIdBySlug['mobile'],
    description:
      'Build cross-platform mobile apps for restaurant management. Work with a small, highly skilled team to ship features quickly and reliably.',
    requirements: [
      '2+ years of Flutter',
      'Dart proficiency',
      'State management (Bloc or Riverpod)',
      'REST API integration',
    ],
    salaryRange: '$2,500 - $3,500 USD/month',
    modality: 'hybrid',
    experience: 'semi-senior',
    createdAt: new Date('2026-03-09T08:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-33',
    title: 'Platform Engineer',
    company: 'Configu',
    location: 'Remote',
    roleId: roleIdBySlug['devops'],
    description:
      'Build developer tooling and internal platform capabilities for engineering teams worldwide. Focus on developer experience, reliability, and self-service infrastructure.',
    requirements: [
      'Experience building internal platforms or developer tools',
      'Go or Python',
      'Kubernetes and Helm expertise',
      'Strong communication skills',
    ],
    salaryRange: '$6,000 - $8,000 USD/month',
    modality: 'remote',
    experience: 'senior',
    createdAt: new Date('2026-03-09T09:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-34',
    title: 'BI Developer',
    company: 'Cencosud',
    location: 'Santiago, Chile',
    roleId: roleIdBySlug['data-science'],
    description:
      'Design and maintain business intelligence solutions for retail operations across Latin America. Translate business needs into robust data models and dashboards.',
    requirements: [
      'Experience with Power BI or Tableau',
      'Strong SQL skills',
      'Data warehousing knowledge',
      'Retail domain knowledge is a plus',
    ],
    salaryRange: 'CLP 2,500,000 - 3,500,000/month',
    modality: 'onsite',
    experience: 'mid',
    createdAt: new Date('2026-03-09T10:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-35',
    title: 'Junior UI/UX Designer',
    company: 'Envíame',
    location: 'Santiago, Chile',
    roleId: roleIdBySlug['ui-ux-design'],
    description:
      'Assist the design team in creating wireframes, prototypes, and visual assets for our logistics platform. Great opportunity to grow in a collaborative environment.',
    requirements: [
      'Degree or bootcamp in UX/UI Design',
      'Basic Figma skills',
      'Understanding of UX principles',
      'Attention to detail',
    ],
    salaryRange: 'CLP 1,200,000 - 1,600,000/month',
    modality: 'hybrid',
    experience: 'junior',
    createdAt: new Date('2026-03-09T11:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-36',
    title: 'QA Automation Lead',
    company: 'Nubiral',
    location: 'Buenos Aires, Argentina',
    roleId: roleIdBySlug['qa-testing'],
    description:
      'Lead a team of automation engineers and define the testing strategy for cloud-based enterprise solutions. Drive adoption of testing best practices company-wide.',
    requirements: [
      '5+ years in QA with 2+ in leadership',
      'Test automation architecture experience',
      'Cloud testing knowledge',
      'Agile coaching skills',
    ],
    salaryRange: '$4,500 - $6,000 USD/month',
    modality: 'hybrid',
    experience: 'senior',
    createdAt: new Date('2026-03-09T13:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-37',
    title: 'IAM Security Engineer',
    company: 'Mercado Libre',
    location: 'Buenos Aires, Argentina',
    roleId: roleIdBySlug['security'],
    description:
      "Design and operate identity and access management systems for one of Latin America's largest tech companies. Ensure least-privilege principles across thousands of services.",
    requirements: [
      'Experience with IAM platforms (Okta, Auth0)',
      'Zero Trust architecture knowledge',
      'Scripting proficiency',
      'Large-scale systems experience',
    ],
    salaryRange: '$5,000 - $7,000 USD/month',
    modality: 'hybrid',
    experience: 'senior',
    createdAt: new Date('2026-03-09T14:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-38',
    title: 'Product Manager – Platform',
    company: 'Inswitch',
    location: 'Montevideo, Uruguay',
    roleId: roleIdBySlug['product-management'],
    description:
      'Own the roadmap for our payment-as-a-service platform. Work with engineering leads, clients, and regulators to define and prioritize platform capabilities.',
    requirements: [
      '4+ years in PM roles',
      'API products experience',
      'Payments or fintech background',
      'Stakeholder management skills',
    ],
    salaryRange: '$4,500 - $6,000 USD/month',
    modality: 'hybrid',
    experience: 'senior',
    createdAt: new Date('2026-03-10T08:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-39',
    title: 'Next.js Developer',
    company: 'Intellihr',
    location: 'Remote',
    roleId: roleIdBySlug['frontend'],
    description:
      'Build performant, SEO-optimized web applications with Next.js for an HR tech platform serving Australian and Latin American markets.',
    requirements: [
      'Next.js and React expertise',
      'TypeScript',
      'Experience with SSR/SSG patterns',
      'Vercel or AWS deployment',
    ],
    salaryRange: '$3,500 - $4,500 USD/month',
    modality: 'remote',
    experience: 'mid',
    createdAt: new Date('2026-03-10T09:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-40',
    title: 'Go Backend Developer',
    company: 'Lemon Cash',
    location: 'Buenos Aires, Argentina',
    roleId: roleIdBySlug['backend'],
    description:
      'Develop high-performance backend services in Go for our crypto wallet and exchange platform. Work with a small, elite engineering team.',
    requirements: [
      '2+ years of Go',
      'Concurrency patterns knowledge',
      'gRPC or REST API experience',
      'Blockchain basics are a plus',
    ],
    salaryRange: '$3,500 - $4,500 USD/month',
    modality: 'hybrid',
    experience: 'semi-senior',
    createdAt: new Date('2026-03-10T10:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-41',
    title: 'Full Stack Developer (Django + React)',
    company: 'Satellogic',
    location: 'Remote',
    roleId: roleIdBySlug['full-stack'],
    description:
      'Build internal tools and customer-facing applications for processing and visualizing satellite imagery data. Work at the intersection of geospatial tech and web development.',
    requirements: [
      'Django and React experience',
      'PostgreSQL/PostGIS',
      'REST API design',
      'Interest in geospatial technology',
    ],
    salaryRange: '$4,000 - $5,500 USD/month',
    modality: 'remote',
    experience: 'mid',
    createdAt: new Date('2026-03-10T11:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-42',
    title: 'Senior React Native Developer',
    company: 'Pomelo',
    location: 'Buenos Aires, Argentina',
    roleId: roleIdBySlug['mobile'],
    description:
      'Lead mobile development efforts for a card-issuing fintech. Define architecture patterns, review code, and drive performance improvements.',
    requirements: [
      '5+ years of React Native',
      'Deep understanding of the JS bridge and native modules',
      'Mentoring experience',
      'Fintech domain knowledge preferred',
    ],
    salaryRange: '$5,000 - $7,000 USD/month',
    modality: 'hybrid',
    experience: 'senior',
    createdAt: new Date('2026-03-10T13:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-43',
    title: 'Junior DevOps Engineer',
    company: 'Hexacta',
    location: 'Buenos Aires, Argentina',
    roleId: roleIdBySlug['devops'],
    description:
      'Assist in managing CI/CD pipelines and cloud infrastructure for client projects. Learn from senior engineers and gain hands-on experience with modern DevOps tooling.',
    requirements: [
      'Basic knowledge of Linux',
      'Familiarity with Docker',
      'Eager to learn cloud technologies',
      'Good communication skills',
    ],
    salaryRange: '$1,500 - $2,200 USD/month',
    modality: 'hybrid',
    experience: 'junior',
    createdAt: new Date('2026-03-10T14:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-44',
    title: 'Senior Data Engineer',
    company: 'Bantotal',
    location: 'Montevideo, Uruguay',
    roleId: roleIdBySlug['data-science'],
    description:
      'Design and build reliable data pipelines and lake architecture for banking clients across Latin America. Define data governance standards and mentor data engineers.',
    requirements: [
      '5+ years in data engineering',
      'Spark and distributed processing',
      'Data lake/warehouse design',
      'Banking domain knowledge',
    ],
    salaryRange: '$5,000 - $6,500 USD/month',
    modality: 'hybrid',
    experience: 'senior',
    createdAt: new Date('2026-03-11T08:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-45',
    title: 'Design Systems Designer',
    company: 'Nuvemshop',
    location: 'São Paulo, Brazil',
    roleId: roleIdBySlug['ui-ux-design'],
    description:
      'Own and evolve our design system used by 20+ product teams. Create reusable components, documentation, and governance processes to ensure consistency across the platform.',
    requirements: [
      'Experience maintaining a design system',
      'Figma and tokens expertise',
      'Collaboration with engineering',
      'Documentation skills',
    ],
    salaryRange: 'R$9,000 - R$13,000/month',
    modality: 'hybrid',
    experience: 'semi-senior',
    createdAt: new Date('2026-03-11T09:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-46',
    title: 'QA Engineer – Mobile',
    company: 'Naranja X',
    location: 'Córdoba, Argentina',
    roleId: roleIdBySlug['qa-testing'],
    description:
      'Ensure quality for our iOS and Android banking apps. Plan test strategies, execute automation, and collaborate with developers to achieve high release confidence.',
    requirements: [
      'Mobile testing experience (iOS and Android)',
      'Automation with Appium or Detox',
      'Bug lifecycle management',
      'Agile team experience',
    ],
    salaryRange: '$2,200 - $3,200 USD/month',
    modality: 'hybrid',
    experience: 'semi-senior',
    createdAt: new Date('2026-03-11T10:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-47',
    title: 'GRC Security Analyst',
    company: 'Bancolombia',
    location: 'Medellín, Colombia',
    roleId: roleIdBySlug['security'],
    description:
      "Support the governance, risk, and compliance program for one of Colombia's largest banks. Assess controls, manage audits, and drive ISO 27001 certification activities.",
    requirements: [
      'Knowledge of ISO 27001 and NIST CSF',
      'Risk assessment experience',
      'Audit management skills',
      'Strong documentation skills',
    ],
    salaryRange: 'COP 6,000,000 - 8,000,000/month',
    modality: 'onsite',
    experience: 'mid',
    createdAt: new Date('2026-03-11T11:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-48',
    title: 'Senior Product Manager',
    company: 'Ank',
    location: 'Buenos Aires, Argentina',
    roleId: roleIdBySlug['product-management'],
    description:
      'Lead product strategy and execution for a B2B SaaS platform in the logistics sector. Work directly with the CEO and CTO to shape the company roadmap.',
    requirements: [
      '5+ years in PM roles',
      'B2B SaaS experience',
      'Strong analytical skills',
      'Leadership experience',
    ],
    salaryRange: '$5,000 - $7,000 USD/month',
    modality: 'hybrid',
    experience: 'senior',
    createdAt: new Date('2026-03-11T12:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-49',
    title: 'React Developer – E-commerce',
    company: 'Tiendanube',
    location: 'Buenos Aires, Argentina',
    roleId: roleIdBySlug['frontend'],
    description:
      'Build scalable storefronts and checkout flows for thousands of merchants on our platform. Work with performance and accessibility as first-class concerns.',
    requirements: [
      'React expertise',
      '3+ years of frontend development',
      'Web performance optimization skills',
      'Accessibility (WCAG) knowledge',
    ],
    salaryRange: '$3,000 - $4,000 USD/month',
    modality: 'hybrid',
    experience: 'mid',
    createdAt: new Date('2026-03-11T13:00:00.000Z'),
    isActive: true,
  },
  {
    id: 'job-50',
    title: 'Senior Full Stack Engineer',
    company: 'Vercel (contractor)',
    location: 'Remote',
    roleId: roleIdBySlug['full-stack'],
    description:
      'Contribute to internal tooling and developer experience features for a globally distributed team. High autonomy, high impact, and a world-class engineering culture.',
    requirements: [
      '5+ years of full stack experience',
      'Deep React and Node.js knowledge',
      'Experience with edge computing or serverless',
      'Open source contributions preferred',
    ],
    salaryRange: '$7,000 - $10,000 USD/month',
    modality: 'remote',
    experience: 'senior',
    createdAt: new Date('2026-03-11T14:00:00.000Z'),
    isActive: true,
  },
];

async function main() {
  console.log('Seeding database...');

  await prisma.role.createMany({ data: roles, skipDuplicates: true });
  console.log(`✓ ${roles.length} roles created`);

  await prisma.job.createMany({ data: jobs, skipDuplicates: true });
  console.log(`✓ ${jobs.length} jobs created`);

  console.log('Seed completed successfully');
}

main()
  .catch(e => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
